# Generated by Django 5.2.7 on 2025-11-24 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksApp', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='listing',
            name='condition',
            field=models.CharField(choices=[('used', 'Używana'), ('new', 'Nowa')], default='new', max_length=10),
        ),
        migrations.AlterField(
            model_name='listing',
            name='listing_type',
            field=models.CharField(choices=[('sale', 'Sprzedaż'), ('exchange', 'Wymiana')], default='sale', max_length=10),
        ),
    ]
