# Generated by Django 5.2.7 on 2025-11-13 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksApp', '0003_publisher_book_publisher'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pages',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
