# Generated by Django 5.2.7 on 2025-11-29 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('booksApp', '0004_publisher_alter_message_options_and_more'),
        ('booksApp', '0006_book_average_rating'),
    ]

    operations = [
    ]
