# Generated by Django 5.2.7 on 2025-11-29 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksApp', '0007_merge_20251129_2054'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='allow_exchange',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ExchangeOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted_a', models.BooleanField(default=False)),
                ('accepted_b', models.BooleanField(default=False)),
                ('rejected', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers_a', to='booksApp.book')),
                ('books_b', models.ManyToManyField(related_name='offers_b', to='booksApp.book')),
                ('chosen_book_b', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chosen_offer_b', to='booksApp.book')),
                ('user_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers_a_users', to=settings.AUTH_USER_MODEL)),
                ('user_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers_b_users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
