# Generated by Django 5.2.7 on 2025-11-29 23:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booksApp', '0008_listing_allow_exchange_exchangeoffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='exchange_offer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='booksApp.exchangeoffer'),
        ),
    ]
